exp:
  config_dir: /Users/vadimtitov/CLIPResearch/configs/
  config: multidomain.yaml
  project: TestEvaluation
  name: test
  tags: 
    - mapper
  seed: 12
  root: .
  notes: empty notes
  step_save: 10000
  trainer: td_multiple_base
training:
  iter_num: 800
  batch_size: 12
  device: cuda:0
  generator: stylegan2
  patch_key: cin_mult
  train_domain_list: text_domains/domain_list_20.txt
  test_domain_list: text_domains/domain_list_20.txt
  mixing_noise: 0.9
  auto_layer_iters: 0
mapper_config:
  backbone_type: shared
  mapper_type: residual_channelin
  activation: relu
  input_dimension: 512
  width: 512
  head_depth: 2
  backbone_depth: 4
  no_coarse: false
  no_fine: false
  no_medium: false
optimization_setup:
  visual_encoders:
    - ViT-B/32
    - ViT-B/16
  loss_funcs:
    - direction
  loss_coefs:
    - 1.0
  optimizer:
    weight_decay: 0.0
    lr: 0.00005
    betas:
    - 0.9
    - 0.999
generator_args:
  checkpoint_path: pretrained/StyleGAN2/stylegan2-ffhq-config-f.pt
logging:
  log_every: 10
  log_images: 20
  latents_to_edit: []
  image_embedding_log: false
  truncation: 0.7
  num_grid_outputs: 1
evaluation:
  is_on: true
  vision_models:
    - ViT-L/14
  step: 1000
  data_size: 1000
  batch_size: 50
checkpointing:
  is_on: false
  start_from: false
  step_backup: 10000000