exp:
  config_dir: /Users/vadimtitov/CLIPResearch/configs/
  config: multidomain.yaml
  project: TdMultiple
  name: Test
  tags: 
    - mapper
  seed: 12
  root: .
  notes: empty notes
  step_save: 1000
  trainer: td_multiple_resample_and_convex
training:
  iter_num: 10000
  batch_size: 8
  device: cuda:0
  generator: stylegan2
  patch_key: cin_mult
  train_domain_list: text_domains/domain_list_20.txt
  test_domain_list: text_domains/domain_list_20.txt
  mixing_noise: 0.9
convex_hull:
  do: true
resample:
  do: true
  divergence: 0.95
mapper_config:
  backbone_type: shared
  mapper_type: residual_channelin
  activation: relu
  input_dimension: 512
  width: 512
  head_depth: 2
  backbone_depth: 4
  no_coarse: false
  no_fine: false
  no_medium: false
optimization_setup:
  visual_encoders:
    - ViT-B/32
    - ViT-B/16
  loss_funcs:
    - direction
    - tt_direction
  loss_coefs:
    - 1.0
    - 0.4
  optimizer:
    weight_decay: 0.0
    lr: 0.00005
    betas:
    - 0.9
    - 0.999
generator_args:
  checkpoint_path: pretrained/StyleGAN2/stylegan2-ffhq-config-f.pt
logging:
  log_every: 10
  log_images: 100
  latents_to_edit: []
  image_embedding_log: false
  truncation: 0.7
  num_grid_outputs: 1
checkpointing:
  is_on: false
  start_from: false
  step_backup: 10000000