exp:
  config_dir: configs
  config: td_single_horse.yaml
  project: Test
  tags:
    - after demodulation
  name: Tests
  seed: 12
  root: .
  notes: empty notes
  logging: true
  step_save: 100
  trainer: td_single
training:
  iter_num: 150
  batch_size: 8
  device: cuda:0
  generator: stylegan2
  phase: conv_kernel
  patch_key: original
  source_class: Horse
  target_class: Pony
  auto_layer_k: 16
  auto_layer_iters: 0
  auto_layer_batch: 8
  mixing_noise: 0.9
optimization_setup:
  visual_encoders: 
    - ViT-B/32
    - ViT-B/16
  loss_funcs:
    - direction
    - indomain
  loss_coefs:
    - 1.0
    - 0.5
  g_reg_every: 4
  optimizer:
    weight_decay: 0.0
    lr: 0.02
    betas:
    - 0.9
    - 0.999
generator_args:
  checkpoint_path: pretrained/StyleGAN2/stylegan2-horse-config-f.pt
  img_size: 256
logging:
  log_every: 10
  log_images: 20
  latents_to_edit: []
  truncation: 0.5
  num_grid_outputs: 1
checkpointing:
  is_on: false
  start_from: false
  step_backup: 100000