exp:
  config_dir: configs
  config: td_single_ffhq.yaml
  project: Test
  tags:
    - stylespace
  name: Test
  seed: 12
  root: .
  notes: empty notes
  logging: true
  step_save: 20
  trainer: td_single
training:
  iter_num: 300
  batch_size: 4
  device: cuda:0
  generator: stylegan2
  phase: mapping
  patch_key: cin_mult
  source_class: Photo
  target_class: 3D Render in the Style of Pixar
  auto_layer_k: 16
  auto_layer_iters: 0
  auto_layer_batch: 8
  mixing_noise: 0.9
optimization_setup:
  visual_encoders: 
    - ViT-B/32
    - ViT-B/16
  loss_funcs:
    - direction
  loss_coefs:
    - 1.0
  g_reg_every: 4
  optimizer:
    weight_decay: 0.0
    lr: 0.1
    betas:
    - 0.9
    - 0.999
generator_args:
  checkpoint_path: pretrained/StyleGAN2/stylegan2-ffhq-config-f.pt
logging:
  log_every: 10
  log_images: 20
  latents_to_edit: []
  truncation: 0.7
  num_grid_outputs: 1
checkpointing:
  is_on: false
  start_from: false
  step_backup: 100000